name: Test Ansible Playbook

on:
  push:
    branches: [ master ]
    paths:
      - 'RemoteFiles/**'
      - '.github/workflows/test-ansible.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'RemoteFiles/**'
      - '.github/workflows/test-ansible.yml'
      - 'Dockerfile'

jobs:
  test-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        run: |
          make docker-build
          make docker-test

      - name: Clean up
        if: always()
        run: make docker-clean 